### PR TITLE
API implementation overhaul

### PR DESCRIPTION
**Pull request by michaelherger**
Hi Philippe,

here's my suggested refactor of all things Youtube API interaction:

- all calls to the backend are implemented in the new API class
- API calls are cached in LMS to speed up interaction 
- main navigation is broken out into smaller methods, mostly wrappers around the API calls
- youtube playlists and channels are handled like, well, playlists: playing them would result in multiple items being queued up in LMS
- don't request track/video details for every item separately, but grab as many in one go as possible (up to 50)

Have fun :-)

### CODE REVIEW

**Comment by philippe44** [comment]
Thanks Michael for the huge refactoring. It's at the same time fantastic but killing me as well :-). I'm so bad at Perl +LMS that it will take me a few days to understand all the modifications you've done while I was up-to-date with Triode's version. Don't get me wrong, this is really great, was much needed and could never have done it by myself... just a few extra headaches to come !

**Comment by mherger** [comment]
It's worth the effort, trust me :-P. The code imho is much cleaner, and easier to be re-used in other ways. Eg. the youtubechannel:// protocol handler you'd like to implement would call the same abstract API search call as in other places.

**Comment by mherger** [comment]
One more thing: don't try to understand change by change. Don't try to read the diff. It's basically a re-write of the navigation, there are too many changes. Just read the new code. I know, all those callbacks can be confusing. But once you've understood how the new code works, you won't bother reading the diff again.

**Comment by philippe44** [comment]
I absolutely agree, and I will go through it, have no doubt ! One thing, I ran into an error that was already in my code. The region code cannot be a language code (works in some places like FR, but when language code is EN, it fails. Is there an API to get country vs language in LMS ?

**Comment by mherger** [comment]
No, country is not known in LMS at all.

**Comment by philippe44** [comment]
yes, I've already ditched the whole old files. I'll understand firs the basic video search with the callback structure and then will expand from that. At least, I know what is the "intention" of the plugin where when I started I had no idea at all and that was a real nightmare, on top of the HTTPS and Perl inheritance system that was not clear to me

**Comment by philippe44** [comment]
okay, for Country then it will be manual
I dont' want to offend my UK friends or US friends :-)

**Comment by mherger** [comment]
You could have some reasonable default value per language, then let the user change it in the prefs. Eg. EN -> US, DE -> DE.

**Comment by mherger** [comment]
Are you Canadian or French?

**Comment by philippe44** [comment]
French
if I set EN-US, all the British community of LMS users are going to kill me - and they are many

**Comment by philippe44** [comment]
that would be my last contribution to LMS

**Comment by philippe44** [comment]
Although I'm still dreaming of Sonos synchro and bring back Rapshody (AES) to legacy devices

**Comment by mherger** [comment]
The code is supposed to be two letters only: "The regionCode parameter instructs the API to return search results for the specified country. The parameter value is an ISO 3166-1 alpha-2 country code."

https://www.iso.org/obp/ui/#search/code/

**Comment by philippe44** [comment]
oh well I'll import the table and make some deduction, alphabetical order

**Comment by philippe44** [comment]
wil let these as param anyway
with the changes you've made, a channel can be a favorite as well ?

**Comment by philippe44** [comment]
there is nothing LMS can query from the computer ?
or perl ?

**Comment by mherger** [comment]
No, I haven't implemented a protocol handler for channels (see the forum thread)

**Comment by philippe44** [comment]
like locale::country

**Comment by mherger** [comment]
I really wouldn't worry too much about the country. Really only do a mapping for the language codes which don't exist as a country. Most US users probably wouldn't see any difference if they were served EN results. And if they notice, then this probably teaches them a lesson :-)

**Comment by philippe44** [comment]
that would UK result, no ?
For the favorite, understood and I guess it will be easy after the work you have done

**Comment by philippe44** [comment]
so thanks again, its getting awfully late for me as I've traveled east to west, so double trouble

**Pull request merged**
